sudo: true
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=1.9,<1.10"
    - DJANGO=">=1.10,<1.11"
    - DJANGO=">=1.11,<2.0"
addons:
  postgresql: "9.6"
install:
  - pip install -q coverage coveralls flake8 Django$DJANGO django-nose>=1.4
before_script:
  - psql -c 'CREATE DATABASE querybuilder;' -U postgres
  - psql -U postgres -c "create extension postgis;"
script:
  - flake8 ./querybuilder
  - coverage run setup.py test
  - coverage report --fail-under=90
after_success:
  coveralls
