sudo: required
language: python
python:
  - '2.7'
  - '3.4'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=1.7,<1.8"
    - DJANGO=">=1.8,<1.9"
    - DJANGO=">=1.9,<1.10"
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5
before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'create database "querybuilder";'
  - psql -U postgres querybuilder -c 'create extension "uuid-ossp";'
install:
  - pip install -q coverage coveralls flake8 Django$DJANGO django-nose>=1.4
script:
  - flake8 ./querybuilder
  - coverage run setup.py test
  - coverage report --fail-under=91
after_success:
  coveralls
