sudo: false
language: python
python:
  - '2.7'
  - '3.4'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=1.7,<1.8"
    - DJANGO=">=1.8,<1.9"
    - DJANGO=">=1.9,<1.10"
#addons:
#  postgresql: '9.5'
before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
install:
  - pip install -q coverage coveralls flake8 Django$DJANGO django-nose>=1.4
before_script:
  - psql -c 'CREATE DATABASE querybuilder;' -U postgres
script:
  - flake8 ./querybuilder
  - coverage run setup.py test
  - coverage report --fail-under=91
after_success:
  coveralls
