sudo: true
language: python
python:
  - '2.7.11'
  - '3.4'
env:
  global:
    - DB=postgres
    - PGVERSION=9.0
    - PGVERSION=9.1
    - PGVERSION=9.2
    - PGVERSION=9.3
    - PGVERSION=9.4
    - PGVERSION=9.5
  matrix:
    - DJANGO=">=1.7,<1.8"
    - DJANGO=">=1.8,<1.9"
    - DJANGO=">=1.9,<1.10"
language: c
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/petere/6023944/raw/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh
  - sudo pip install --upgrade pip
script: bash ./pg-travis-test.sh
install:
  - pip install -q coverage coveralls flake8 Django$DJANGO django-nose>=1.4
before_script:
  - psql -c 'CREATE DATABASE querybuilder;' -U postgres
script:
  - flake8 ./querybuilder
  - coverage run setup.py test
  - coverage report --fail-under=90
after_success:
  coveralls
